### ISSUE TITLE
Publish first release?

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-xmlsec#7]
Any plans on when to do the first release?

Might be a good idea to do one before #6 and then one shortly after that _with_ #6.

/cc @Martinffx @gastaldi

**Comment by famod** [comment]
0.0.1 was released shortly after I created this issuse, right @gastaldi?

**Comment by gastaldi** [comment]
@famod yes, that's right

**Comment by famod** [comment]
Ok, thanks! Too bad @martinffx seems to be inactive.

**Comment by martinffx** [comment]
Sorry,  I've not got around to this.

Got some time this week so hopefully I can wrap it up

**Comment by martinffx** [comment]
@famod pushed 1.0.0 release

**Comment by famod** [comment]
Thanks @martinffx!
