### ISSUE TITLE
Release 2.0.0.Alpha1

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-xmlsec#85]
The [release workflow](https://github.com/quarkiverse/quarkus-xmlsec/blob/main/.github/workflows/release.yml) cannot upload the artifacts to `s01.oss.sontatype.org`:

```
[INFO] [INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ quarkus-xmlsec-parent ---
[INFO] [INFO] Uploading to oss.sonatype: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/io/quarkiverse/xmlsec/quarkus-xmlsec-parent/2.0.0.Alpha1/quarkus-xmlsec-parent-2.0.0.Alpha1.pom
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Reactor Summary for Quarkus - XMLSec - Parent 2.0.0.Alpha1:
[INFO] [INFO] 
[INFO] [INFO] Quarkus - XMLSec - Parent .......................... FAILURE [  3.207 s]
[INFO] [INFO] Quarkus - XMLSec - BOM ............................. SKIPPED
[INFO] [INFO] Quarkus - XMLSec ................................... SKIPPED
[INFO] [INFO] Quarkus - XMLSec - Deployment ...................... SKIPPED
[INFO] [INFO] Quarkus - XMLSec - Integration Tests ............... SKIPPED
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  3.491 s
[INFO] [INFO] Finished at: 2023-02-08T09:10:10Z
[INFO] [INFO] ------------------------------------------------------------------------
Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project quarkus-xmlsec-parent: Failed to deploy artifacts: Could not transfer artifact io.quarkiverse.xmlsec:quarkus-xmlsec-parent:pom:2.0.0.Alpha1 from/to oss.sonatype (https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/): authentication failed for https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/io/quarkiverse/xmlsec/quarkus-xmlsec-parent/2.0.0.Alpha1/quarkus-xmlsec-parent-2.0.0.Alpha1.pom, status: 401 Unauthorized -> [Help 1]
```

**Comment by ppalaga** [comment]
Any idea why this happens @gastaldi ? 

Maybe the secrets need to be set differently, now that I started relying on settings.xml set up by `actions/setup-java@v3`?

**Comment by gastaldi** [comment]
@ppalaga that's weird, maybe because `./mvnw` is being used instead? I've updated the scripts in https://github.com/quarkiverse/quarkus-xmlsec/pull/86 to the latest actions and settings. Hopefully that should work

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkiverse/quarkus-xmlsec/actions/runs/4124668633/jobs/7124203659

**Comment by ppalaga** [comment]
@gastaldi thanks, it worked. I dared to move the attributes.adoc to a separate commit before the release, so that we do not need to do the manual tag juggling: https://github.com/quarkiverse/quarkus-xmlsec/blob/main/.github/workflows/release.yml#L55-L61

**Comment by gastaldi** [comment]
Ahhh fantastic!! Can you provide a PR updating the official template in https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/release.yml ?

**Comment by ppalaga** [comment]
Here is the PR: https://github.com/quarkusio/quarkus/pull/31046

**Comment by gsmet** [comment]
I might miss something but how is the version in the attributes updated given the version will be set later by release:prepare?

**Comment by gastaldi** [comment]
@gsmet The version is taken from the project.yml, not the pom.xml

**Comment by ppalaga** [comment]
Yes, there is a plugin in doc module reading `project.yaml` and setting Maven properties out of it that are then used by the resources filtering.
